name: Build and Upload Assets

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    name: Build and Upload Assets
    strategy:
      fail-fast: false
      matrix:
        kind: ['windows', 'linux', 'macos']
        include:
          - kind: windows
            os: ['windows-latest']
            target: win-x64
          - kind: linux
            os: ['ubuntu-latest']
            target: linux-x64
          - kind: macos
            os: ['macos-latest']
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download MAPPER_COMMIT.txt from the triggered GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Construct the download URL from the release event data
          MAPPER_COMMIT_URL=$(echo ${{ github.event.release.assets }} | jq -r '.[] | select(.name == "MAPPER_COMMIT.txt").browser_download_url')
          
          # Use curl to download the MAPPER_COMMIT.txt file
          curl -L -o MAPPER_COMMIT.txt -H "Authorization: token $GITHUB_TOKEN" $MAPPER_COMMIT_URL

      - name: Update MAPPER_VERSION in appsettings.json
        run: |
          MAPPER_COMMIT=$(cat MAPPER_COMMIT.txt)
          jq --arg MAPPER_COMMIT "$MAPPER_COMMIT" '.MAPPER_VERSION = $MAPPER_COMMIT' ./src/GameHook.WebAPI/appsettings.json > ./src/GameHook.WebAPI/appsettings.json.tmp && mv ./src/GameHook.WebAPI/appsettings.json.tmp ./src/GameHook.WebAPI/appsettings.json
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 8.0.x

      - name: Build Project
        shell: bash
        run: |
          # Variables
          commithash=$(git describe --long --always --dirty --exclude=* --abbrev=8)
          tag=$(git describe --tags --abbrev=0)
          release_name="GameHook-${{ matrix.target }}-$tag"
          echo "commithash is $commithash"
          echo "tag is $tag"
          echo "release_name is $release_name"

          echo "Building GameHook.WebAPI"
          echo "dotnet publish src/GameHook.WebAPI/GameHook.WebAPI.csproj -r ${{ matrix.target }} -c Release -o deploy /property:PublishSingleFile=true /property:Version=$tag /property:InformationalVersion=$tag+$commithash"
          dotnet publish src/GameHook.WebAPI/GameHook.WebAPI.csproj -r ${{ matrix.target }} -c Release -o deploy /property:PublishSingleFile=true /property:Version=$tag /property:InformationalVersion=$tag+$commithash

          if [ "${{ matrix.kind }}" == "windows" ]; then
            echo "Building GameHook.WPF"

            echo "dotnet publish src/GameHook.WPF/GameHook.WPF.csproj -r ${{ matrix.target }} -c Release -o deploy /property:PublishSingleFile=true /property:Version=$tag /property:InformationalVersion=$tag+$commithash"
            dotnet publish src/GameHook.WPF/GameHook.WPF.csproj -r ${{ matrix.target }} -c Release -o deploy /property:PublishSingleFile=true /property:Version=$tag /property:InformationalVersion=$tag+$commithash
          fi

          # Rename binaries.
          if [ "${{ matrix.kind }}" == "windows" ]; then
            cp ./deploy/GameHook.WPF.exe ./deploy/GameHook.exe
            cp ./deploy/GameHook.WebAPI.exe ./deploy/GameHook.Console.exe

            7z a -tzip "${release_name}.zip" "./deploy/GameHook.exe"
            7z a -tzip "${release_name}-console-only.zip" "./deploy/GameHook.Console.exe"
          else
            chmod +x ./deploy/GameHook.WebAPI
            cp ./deploy/GameHook.WebAPI ./deploy/GameHook

            cd ./deploy/ && tar czvf "./../${release_name}.tar.gz" GameHook && cd -
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./GameHook-*.zip
            ./GameHook-*.tar.gz
            ./deploy/GameHook.exe
  
  notify:
    name: Notify Users
    runs-on: ubuntu-latest
    needs:
      - build-and-upload
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_APP_UPDATES_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'A new version of GameHook has been released. Version ${{ github.event.release.tag_name }} is now available. <https://github.com/gamehook-io/gamehook/releases/tag/${{ github.event.release.tag_name }}>'